---

# Image settings https://github.com/docker-library/docs/tree/master/cassandra

# CASSANDRA_SEEDS -> specify ~3 seed nodes for dc.
# They are used by gossip for bootstrapping new nodes joining a cluster.

# Ports:
#    7199: cassandra JMX
#    1099  kafka jmx
#    9042: CQL
#    9200: ElasticSearch HTTP
#    2181: zookeper
#    9092: kafka

version: '3.3'
services:

    cs-elassandra:
      network_mode: host
      image: strapdata/elassandra:5.5.0.8
      restart: on-failure
      volumes:
        - /cyberdata/cyber-search/elassandra/lib:/var/lib/cassandra
        - /cyberdata/cyber-search/elassandra/log:/var/log/cassandra
      environment:
         CASSANDRA_DC: DEVELOPMENT
         CASSANDRA_CLUSTER_NAME: CYBER_SEARCH

    cs-chain-pumps:
      network_mode: host
      image: cybernode/cs-chain-pumps:release-v1.0.0.M1
      restart: on-failure
      environment:
         CS_CHAINS_TO_PUMP: BITCOIN, BITCOIN_CASH, ETHEREUM, ETHEREUM_CLASSIC
         CASSANDRA_HOSTS: localhost
#         BITCOIND_URL: http://cyber:cyber@cs-bitcoind:8332
#         ABC_URL: http://bitcoin:password@cs-abc:18332
#         ETHEREUM: http://cyber:cyber@cs-parity-eth:8545
#         ETHEREUM_CLASSIC: http://cyber:cyber@cs-parity-etc:18545
         CS_LOG_LEVEL: DEBUG

    cs-search-api:
      network_mode: host
      image: cybernode/cs-search-api:release-v1.0.0.M1
      restart: on-failure
      environment:
         CASSANDRA_HOSTS: localhost
         CS_LOG_LEVEL: DEBUG