---

# Image settings https://github.com/docker-library/docs/tree/master/cassandra

# CASSANDRA_SEEDS -> specify ~3 seed nodes for dc.
# They are used by gossip for bootstrapping new nodes joining a cluster.

# Ports:
#    9042: CQL
#    9200: ElasticSearch HTTP
#    9300: ElasticSearch transport
#    2181: Zookeper
#    9092: Kafka
#    9000: Kafka Manager
#    3030: Kafka Browser

version: '3.3'
services:

  elassandra:
    container_name: cassandra
    image: strapdata/elassandra:5.5.0.8
    volumes:
      - /opt/cyberfund/search/elassandra:/var/lib/cassandra
      - /opt/cyberfund/search/elassandra/logs:/var/log/cassandra
    environment:
       CASSANDRA_DC: DEVELOPMENT
       CASSANDRA_CLUSTER_NAME: CYBER_SEARCH
    ports:
      - "9042:9042"
      - "9200:9200"
      - "9300:9300"

  cs-zoo:
    network_mode: host
    container_name: zoo
    image: confluentinc/cp-zookeeper:4.0.0
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - /opt/cyberfund/search/zoo/data:/var/lib/zookeeper/data
      - /opt/cyberfund/search/zoo/log:/var/lib/zookeeper/log

  cs-kafka:
    network_mode: host
    container_name: kafka
    image: confluentinc/cp-kafka:4.0.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_JMX_PORT: 1099
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - /opt/cyberfund/search/kafka:/var/lib/kafka/data

  cs-kafka-manager:
    network_mode: host
    image: hlebalbau/kafka-manager:1.3.3.15
    environment:
      ZK_HOSTS: "localhost:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null

  kafka-rest:
    network_mode: host
    image: confluentinc/cp-kafka-rest:4.0.0
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_REST_LISTENERS: http://localhost:8082
      KAFKA_REST_HOST_NAME: localhost

      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: 'GET,OPTIONS,HEAD,POST,PUT,DELETE'
      KAFKA_REST_LOG4J_ROOT_LOGLEVEL: ERROR

  fast-data-dev:
    network_mode: host
    image: landoop/fast-data-dev:cp3.3.1
    environment:
       WEB_ONLY: 1
       RUNTESTS: 0
       SAMPLEDATA: 0

  prometheus:
    network_mode: host
    container_name: prometheus
    restart: on-failure
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"

  grafana:
    network_mode: host
    container_name: grafana3
    restart: on-failure
    image: grafana/grafana:5.0.0-beta4
#    ports:
#      - "3000:3000"