version: 2

# This config file uses YAML aliases
# http://blog.daemonl.com/2016/02/yaml.html
# https://github.com/cyklo/Bukkit-OtherBlocks/wiki/Aliases-(advanced-YAML-usage)
aliases:

  # Common configuration for all jobs
  - &defaults
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk

jobs:

  build_project:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "build.gradle" }}
            - project-dependencies
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
      - run:
          name: Test and build kafka-connectors project
          command: ./gradlew clean build
      - save_cache:
          key: project-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/


  deploy_pumps_ethereum_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Ethereum Pump Image
           command: |
             docker build -t build/pump-eth -f ./pumps/ethereum/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/pump-eth cybernode/pumps-ethereum:nightly
             docker push cybernode/pumps-ethereum:nightly
             if [[ "$CIRCLE_TAG" != "" ]]; then
               docker tag build/pump-eth cybernode/pumps-ethereum:$CIRCLE_TAG
               docker push cybernode/pumps-ethereum:$CIRCLE_TAG
             fi

  deploy_dumps_ethereum_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Ethereum Dump Image
           command: |
             docker build -t build/dump-eth -f ./dumps/ethereum/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/dump-eth cybernode/dumps-ethereum:nightly
             docker push cybernode/dumps-ethereum:nightly
             if [[ "$CIRCLE_TAG" != "" ]]; then
               docker tag build/dump-eth cybernode/dumps-ethereum:$CIRCLE_TAG
               docker push cybernode/dumps-ethereum:$CIRCLE_TAG
             fi

workflows:
  version: 2

  search_build:
    jobs:
      - build_project:
      - deploy_pumps_ethereum_image:
          requires:
            - build_project
      - deploy_dumps_ethereum_image:
          requires:
            - build_project