version: 2

# This config file uses YAML aliases
# http://blog.daemonl.com/2016/02/yaml.html
# https://github.com/cyklo/Bukkit-OtherBlocks/wiki/Aliases-(advanced-YAML-usage)
aliases:

  # Common configuration for all jobs
  - &defaults
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk

  - &release_filter
    filters:
      tags:
        only: /.*/
      branches:
        ignore: /.*/

jobs:

  build_project:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "build.gradle" }}
            - project-dependencies
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
      - run:
          name: Build And Test Project
          command: ./gradlew clean build
      - save_cache:
          key: project-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/

# Ethereum Images
  deploy_chain_pumps_ethereum_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Ethereum Pump Image
           command: |
             docker build -t build/pump-ethereum -f ./pumps/ethereum/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/pump-ethereum cybernode/chain-pump-ethereum:$CIRCLE_TAG
             docker push cybernode/chain-pump-ethereum:$CIRCLE_TAG
             docker tag build/pump-ethereum cybernode/chain-pump-ethereum:latest
             docker push cybernode/chain-pump-ethereum:latest

  deploy_chain_dumps_cassandra_ethereum_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Ethereum Dump Image
           command: |
             docker build -t build/dump-cassandra-ethereum -f ./dumps/ethereum/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/dump-cassandra-ethereum cybernode/chain-dump-cassandra-ethereum:$CIRCLE_TAG
             docker push cybernode/chain-dump-cassandra-ethereum:$CIRCLE_TAG
             docker tag build/dump-cassandra-ethereum cybernode/chain-dump-cassandra-ethereum:latest
             docker push cybernode/chain-dump-cassandra-ethereum:latest

  deploy_chain_contract_summary_ethereum_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Ethereum Contract Summary Image
           command: |
             docker build -t build/chain-contract-summary-ethereum -f ./contract-summary/ethereum/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/chain-contract-summary-ethereum cybernode/chain-contract-summary-ethereum:$CIRCLE_TAG
             docker push cybernode/chain-contract-summary-ethereum:$CIRCLE_TAG
             docker tag build/chain-contract-summary-ethereum cybernode/chain-contract-summary-ethereum:latest
             docker push cybernode/chain-contract-summary-ethereum:latest

# Bitcoin images
  deploy_chain_pumps_bitcoin_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Bitcoin Pump Image
           command: |
             docker build -t build/pump-bitcoin -f ./pumps/bitcoin/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/pump-bitcoin cybernode/chain-pump-bitcoin:$CIRCLE_TAG
             docker push cybernode/chain-pump-bitcoin:$CIRCLE_TAG
             docker tag build/pump-bitcoin cybernode/chain-pump-bitcoin:latest
             docker push cybernode/chain-pump-bitcoin:latest

  deploy_chain_dumps_cassandra_bitcoin_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Bitcoin Dump Image
           command: |
             docker build -t build/dump-cassandra-bitcoin -f ./dumps/bitcoin/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/dump-cassandra-bitcoin cybernode/chain-dump-cassandra-bitcoin:$CIRCLE_TAG
             docker push cybernode/chain-dump-cassandra-bitcoin:$CIRCLE_TAG
             docker tag build/dump-cassandra-bitcoin cybernode/chain-dump-cassandra-bitcoin:latest
             docker push cybernode/chain-dump-cassandra-bitcoin:latest

  deploy_chain_contract_summary_bitcoin_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Build Bitcoin Contract Summary Image
           command: |
             docker build -t build/chain-contract-summary-bitcoin -f ./contract-summary/bitcoin/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/chain-contract-summary-bitcoin cybernode/chain-contract-summary-bitcoin:$CIRCLE_TAG
             docker push cybernode/chain-contract-summary-bitcoin:$CIRCLE_TAG
             docker tag build/chain-contract-summary-bitcoin cybernode/chain-contract-summary-bitcoin:latest
             docker push cybernode/chain-contract-summary-bitcoin:latest


# Common images
  deploy_search_api_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Chains Search Api Image
           command: |
             docker build -t build/search-api -f ./search-api/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/search-api cybernode/search-api:$CIRCLE_TAG
             docker push cybernode/search-api:$CIRCLE_TAG
             docker tag build/search-api cybernode/search-api:latest
             docker push cybernode/search-api:latest

  deploy_search_api_docs_image:
     <<: *defaults
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.11.0-ce
       - run:
           name: Chains Search Api Documentation Image
           command: |
             docker build -t build/search-api-docs -f ./docs/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/search-api-docs cybernode/search-api-docs:$CIRCLE_TAG
             docker push cybernode/search-api-docs:$CIRCLE_TAG
             docker tag build/search-api-docs cybernode/search-api-docs:latest
             docker push cybernode/search-api-docs:latest

workflows:
  version: 2

  search_build:
    jobs:
      - build_project:
          filters:
            tags:
              only: /.*/
      - deploy_chain_pumps_ethereum_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_chain_dumps_cassandra_ethereum_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_chain_contract_summary_ethereum_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_chain_pumps_bitcoin_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_chain_dumps_cassandra_bitcoin_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_chain_contract_summary_bitcoin_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_search_api_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_search_api_docs_image:
          <<: *release_filter
          requires:
            - build_project