version: 2


defaults:

  container: &default_container
    working_directory: ~/build
    docker:
      - image: circleci/openjdk:8-jdk

  release_filter: &release_filter
    filters:
      tags:
        only: /^release-.*/
      branches:
        ignore: /.*/


jobs:

  build_project:
    <<: *default_container
    steps:
      - checkout
      - restore_cache:
          keys:
            - project-dependencies-{{ checksum "build.gradle" }}
            - project-dependencies
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/
      - run:
          name: Test and build kafka-connectors project
          command: ./gradlew clean build
      - save_cache:
          key: project-dependencies-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/


  deploy_connectors_image:
     <<: *default_container
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.05.0-ce
       - run:
           name: Build kafka-connectors docker image
           command: |
             docker build -t build/cn-kafka-connectors -f ./devops/cyber-connectors/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/cn-kafka-connectors cybernode/cn-kafka-connectors:$CIRCLE_TAG
             docker push cybernode/cn-kafka-connectors:$CIRCLE_TAG
             docker tag build/cn-kafka-connectors cybernode/cn-kafka-connectors:latest
             docker push cybernode/cn-kafka-connectors:latest


  deploy_bitcoin_processor_image:
     <<: *default_container
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.05.0-ce
       - run:
           name: Build kafka-streams processor for bitcoin
           command: |
             docker build -t build/cs-bitcoin-processor -f ./devops/stream-processing/bitcoin ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/cs-bitcoin-processor cybernode/cs-bitcoin-processor:$CIRCLE_TAG
             docker push cybernode/cs-bitcoin-processor:$CIRCLE_TAG
             docker tag build/cs-bitcoin-processor cybernode/cs-bitcoin-processor:latest
             docker push cybernode/cs-bitcoin-processor:latest


  deploy_search_api_image:
     <<: *default_container
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.05.0-ce
       - run:
           name: Build cyber search api image
           command: |
             docker build -t build/cs-search-api -f ./devops/search-api/search-api ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/cs-search-api cybernode/cs-search-api:$CIRCLE_TAG
             docker push cybernode/cs-search-api:$CIRCLE_TAG
             docker tag build/cs-search-api cybernode/cs-search-api:latest
             docker push cybernode/cs-search-api:latest


workflows:
  version: 2

  search_build:
    jobs:
      - build_project:
          filters:
            tags:
              only: /.*/
      - deploy_connectors_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_bitcoin_processor_image:
          <<: *release_filter
          requires:
            - build_project
      - deploy_search_api_image:
          <<: *release_filter
          requires:
            - build_project