version: '3.0'
services:

  parity-eth:
    container_name: parity-eth
    restart: always
    image: parity/parity:stable
    ports:
      - "8545:8545"
    command: "--db-path /cyberdata --jsonrpc-hosts all --jsonrpc-interface all --jsonrpc-threads 8"
    volumes:
      - /cyberdata/eth:/cyberdata

  parity-etc:
    container_name: parity-etc
    restart: always
    image: parity/parity:stable
    ports:
      - "18545:8545"
    command: "--chain classic --db-path /cyberdata --jsonrpc-hosts all --jsonrpc-interface all --jsonrpc-threads 8"
    volumes:
      - /cyberdata/eth_c:/cyberdata

  bitcoind:
    container_name: bitcoind
    restart: always
    image: ruimarinho/bitcoin-core:0.15.1
    ports:
      - "8332:8332"
    command: "-server -rest -txindex -rpcpassword=fund.cyber -rpcuser=fund.cyber -rpcallowip=0.0.0.0/0"
    volumes:
      - /cyberdata/bitcoind:/home/bitcoin/.bitcoin

  abc:
    container_name: abc
    restart: always
    image: hlebalbau/bitcoin-abc-docker:0.16.1
    ports:
      - "7332:7332"
    command: "bitcoind -server -rest -txindex -rpcpassword=fund.cyber -rpcuser=fund.cyber -rpcallowip=::/0 -rpcport=7332"
    volumes:
      - /cyberdata/abc:/home/bitcoin/.bitcoin