version: '3'
services:

  cs-elassandra:
    image: strapdata/elassandra:2.4.5.6
    volumes:
      - /opt/cyberfund/search/elassandra:/var/lib/cassandra
    ports:
        - "9042:9042"
        - "9200:9200"
        - "9300:9300"
        - "7199:7199"
        - "7000:7000"
        - "7001:7001"
    environment:
      CASSANDRA_DC: LOCAL_DEVELOPMENT
      CASSANDRA_CLUSTER_NAME: CYBERNODE
      CASSANDRA_SEEDS: cs-elassandra2
      CASSANDRA_BROADCAST_ADDRESS: cs-elassandra

  cs-elassandra2:
    image: strapdata/elassandra:2.4.5.6
    volumes:
      - /opt/cyberfund/search/elassandra:/var/lib/cassandra
    ports:
        - "9042:9042"
        - "9200:9200"
        - "9300:9300"
        - "7199:7199"
        - "7000:7000"
        - "7001:7001"
    environment:
      CASSANDRA_DC: LOCAL_DEVELOPMENT
      CASSANDRA_CLUSTER_NAME: CYBERNODE
      CASSANDRA_BROADCAST_ADDRESS: cs-elassandra2


  cs-zoo:
    image: confluentinc/cp-zookeeper:3.3.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - /opt/cyberfund/search/zoo/data:/var/lib/zookeeper/data
      - /opt/cyberfund/search/zoo/log:/var/lib/zookeeper/log


  cs-kafka:
    image: confluentinc/cp-kafka:3.3.0
    ports:
      - "9092:9092"
      - "1099:1099"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: cs-zoo:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://cs-kafka:9092
      KAFKA_JMX_PORT: 1099
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /opt/cyberfund/search/kafka:/var/lib/kafka


  cs-kafka-manager:
    image: hlebalbau/kafka-manager:1.3.3.14
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "cs-zoo:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
    labels:
      kompose.service.type: loadbalancer


  cs-kafka-connect:
    image: cybernode/cn-kafka-connectors:release-0.7.2
    ports:
      - "8083:8083"
    environment:

      CONNECT_REST_ADVERTISED_HOST_NAME: "cs-kafka-connect"
      CONNECT_REST_ADVERTISED_PORT: "8083"
      CONNECT_REST_PORT: 8083

      CONNECT_BOOTSTRAP_SERVERS: cs-kafka:9092
      CONNECT_ZOOKEEPER_CONNECT: cs-zoo:2181

      CONNECT_GROUP_ID: "cybernode"
      CONNECT_CONFIG_STORAGE_TOPIC: "cybernode.config"
      CONNECT_OFFSET_STORAGE_TOPIC: "cybernode.offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "cybernode.status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 5000

      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.converters.ByteArrayConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.converters.ByteArrayConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE: "true"
      CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE: "true"

      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_CONSUMER_MAX_PARTITION_FETCH_BYTES: 10485760
      CONNECT_PRODUCER_MAX_REQUEST_SIZE: 10485760

      CONNECT_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      CONNECT_ACCESS_CONTROL_ALLOW_METHODS: 'GET,OPTIONS,HEAD,POST,PUT,DELETE'

      CONNECT_LOG4J_ROOT_LEVEL: WARN
      CONNECT_LOG4J_LOGGERS: org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR,fund.cyber.node.connectors.source=WARN


  cs-bitcoin-process:
    image: cybernode/cs-bitcoin-processor:release-0.7.2
    environment:
      CASSANDRA_CONNECTION: cs-elassandra
      KAFKA_CONNECTION: cs-kafka:9092
      CS_LOG_LEVEL: WARN
      APPLICATION_ID_SUFFIX: a

  cs-ethereum-process:
    image: cybernode/cs-ethereum-processor:release-0.7.2
    environment:
      KAFKA_CONNECTION: cs-kafka:9092
      CS_LOG_LEVEL: WARN


  cs-search-api:
    image: cybernode/cs-search-api:release-0.7.2
    ports:
      - "80:8085"
    environment:
      ELASTIC_HOST_CONNECTION: cs-elassandra
      ELASTIC_PORT_CONNECTION: 9300
      ELASTIC_CLUSTER_NAME: CYBERNODE
      CASSANDRA_HOST_CONNECTION: cs-elassandra
      KAFKA_CONNECTION: cs-kafka:9092
    labels:
      kompose.service.type: loadbalancer


  cs-kafka-connect-ui:
    image: landoop/kafka-connect-ui:0.9.2
    ports:
      - "9001:8000"
    environment:
      CONNECT_URL: cs-kafka-connect:8083
    labels:
      kompose.service.type: loadbalancer


  cs-btcd:
    image: cybernode/bitcoin-btcd:temp
    ports:
      - "8334:8334"
    command: "--rpcuser=cyber --rpcpass=cyber --rpclisten=0.0.0.0:8334 --notls"
    volumes:
      - /cyberdata:/cyberdata

  cs-parity:
    image: parity/parity:stable
    ports:
      - "8545:8545"
    command: "--db-path /cyberdata --jsonrpc-hosts all --jsonrpc-interface all"
    volumes:
      - /cyberdata:/cyberdata